---
title: "Decreasing Differences in Expert Advice: Evidence from Chess Players"
date: 2024-02-02
author:
  - name: Elias Bouacida
    url: https://www.bouacida.fr
    orcid: 0000-0001-8656-6678
    affiliation: University Paris 8
  - name: Renaud Foucart
    url: https://sites.google.com/site/renaudfoucart/
    affiliation: Lancaster University Management School
    orcid: 0000-0003-0611-6146
  - name: Maya Jalloul
    url: https://www.lancaster.ac.uk/lums/people/maya-jalloul/
    affiliation: Lancaster University Management School
    orcid: 0000-0003-3440-3281
doi: ""
categories: 
- Advice
- Control
- Experiment
pub-info:
  reference: >-
    <a href="https://www.bouacida.fr/">Elias Bouacida</a>, <a href="https://sites.google.com/site/renaudfoucart/">Renaud Foucart</a>,  <a href="https://www.lancaster.ac.uk/lums/people/maya-jalloul/">Maya Jalloul</a>"Decreasing Differences in Expert Advice: Evidence from Chess Players"
  # links:
  #   - name: Code
  #     url: https://github.com/RenaudFouc/PreferenceProcedure
  #     icon: fa-brands fa-github
  #   - name: Data
  #     url: https://doi.org/10.57745/ORMINQ
  #     doi: 10.57745/ORMINQ
  #     icon: fa-solid fa-table
sidebar: false    
---

## Abstract

We study the impact of external advice on the relative performance of chess players. We asked players in chess tournaments to evaluate positions in past games and allowed them to revise their evaluation following advice from a high or a low ability player. While our data confirms the theoretical prediction that high-quality advice has the potential to act as a ``great equalizer,'' reducing the difference between high and low ability players, this is not what happens in practice. This is in part because our subjects ignore too much of the advice they receive, but also because low ability players pay -- either due to overconfidence or intrinsic preference -- a higher premium than high ability ones by following their initial idea instead of high-quality advice.
