project:
  type: website

website:
  title: "Elias Bouacida"
  description: "Elias Bouacida is a maître de conférence at the University Paris 8"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: "Research"
      - sidebar:experiment
      - href: elias.qmd
        text: CV
      - about.qmd
  sidebar:
    id: experiment
    title: "Experiment"
    style: "floating"
    contents: experiment 
      
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: source

execute: 
  freeze: auto



