project:
  type: website

website:
  title: "Elias Bouacida's academic website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:experiment
      - href: elias.qmd
        text: Elias
      - about.qmd
  sidebar:
    id: experiment
    title: "Experiment"
    style: "floating"
    contents: experiment 
      
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: source

execute: 
  freeze: auto



