project:
  type: website
  render:
    - "*.qmd"
    - "!experiment/*"
  resources: 
    - "*.pdf"
website:
  title: "Elias Bouacida"
  description: "Elias Bouacida is a maître de conférence at the University Paris 8"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: "Research"
      # - sidebar:experiment
      - href: CV.qmd
        text: CV
      - about.qmd
  # sidebar:
  #   id: experiment
  #   title: "Experiment"
  #   style: "floating"
  #   contents: experiment

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

execute: 
  freeze: auto



