---
title: "CV"
sidebar: false
---

I am currently maître de conférence at the University Paris 8 Vincennes -> Saint-Denis.

### Experience

::: {.d-flex .justify-content-between }
::: {}
**University Paris 8 Vincennes -> Saint-Denis**  
*Maître de conférence* (assistant professor)
:::
::: {.text-end}
Saint-Denis, France  
September 2021 -- present
:::
:::

::: {.d-flex .justify-content-between }
::: {}
**Lancaster University Management School**  
*M.J. Dormer Post-doctoral fellow*
:::
::: {.text-end}
Lancaster, United Kingdom  
September 2019 -- August 2021
:::
:::

::: {.d-flex .justify-content-between }
::: {}
**University Paris--Nanterre**  
*ATER* (teaching assistant)
:::
::: {.text-end}
Nanterre, France  
September 2017 -- August 2019
:::
:::


::: {.d-flex .justify-content-between }
::: {}
**University Paris 1 Panthéon--Sorbonne**  
*Contrat doctoral* (PhD fellowship)
:::
::: {.text-end}
Paris, France  
September 2014 -- August 2017
:::
:::

### Education

::: {.d-flex .justify-content-between }
::: {}
**Paris School of Economics, University Paris 1 Panthéon--Sorbonne**  
Ph.D. in Economics
:::
::: {.text-end}
Paris, France  
2019
:::
:::

::: {.d-flex .justify-content-between }
::: {}
**Paris School of Economics, école nationale des ponts et chaussées**  
M.Sc. in Economics
:::
::: {.text-end}
Paris, France  
2014
:::
:::

::: {.d-flex .justify-content-between }
::: {}
**École nationale des ponts et chaussées**  
M.Eng. in Economics
:::
::: {.text-end}
Champs-sur-Marne, France  
2014
:::
:::

### Teaching

**University Paris 8 Vincennes -> Saint-Denis**  

::: {.d-flex .justify-content-between }
::: {}
Microeconomics 1  (1^st^ year)  
Microeconomics 2  (2^nd^ year)  
Quantitative Technics for Economists 4  (2^nd^ year)  
Introduction to R (3^rd^ year)  
Microeconomics of Banking  (2^nd^ year master)  
Preparation to internship and thesis  (1^st^ year master)  
:::
::: {.text-end}
2022--present  
2021--present  
2021--present  
2022--present  
2021--present  
2022--2023
:::
:::

**Lancaster University Management School**

::: {.d-flex .justify-content-between }
::: {}
TA for Experimental and Behavioural Economics
:::
::: {.text-end}
2019--2021  
:::
:::