---
title: "Results from Experiment 1"
execute: 
  echo: false
  warning: false
page-layout: full
---

```{r settings}
library(scales)
library(dplyr)
library(stringr)
library(kableExtra)
```


```{r draws}

dc2 <- 52
dc3 <- 555
dc4 <- 1952
dc5 <- 16247

above_header <- c("About You" = 2, " " = 1, "About the Mechanisms" = 6,  "Predictions" = 3)
```

**DISCLAIMER: This is an example of what the results will look like.**

You can find here the results from Experiment 1 carried on by Renaud Foucart and Elias Bouacida. 

The different draws of the DC-Lottery of August XX at 12.50pm are:

<!-- - DC-2:  X, X, so the participant number selected is XX; -->
<!-- - DC-3: X, X, X, the rest in the division by 200 is `r dc3 %% 200`, which is the threshold amount (in cents). -->
<!-- - DC-4: X, X, X, X, so the rest in the division by 3 is `r dc4%%3` and the question for predictions selected is XX. -->
<!-- - DC-5: X, X, X, X, X, so the sequence to match is X, X, X, X, X. -->

The selected mechanism for the allocation of the reward is XX.




```{r expe1}

data1 <- read.csv(file = file.path(file.path('..', 'Data', '2023ResultsExperiment1.csv')))

data1 <- data1 %>% 
  mutate(payment = scales::dollar_format()(payment), 
         your_threshold = scales::dollar_format()(your_threshold)) %>% 
  rename_with( ~ str_to_title(gsub("_", " ", .x, fixed = TRUE))) %>% 
  rename_with( ~ gsub("Rps", "RPS", .x, fixed = TRUE))



kable(data1,
      # col.names = gsub("[_]", " ", names(data3)),
      align= 'c') %>% 
  add_header_above(above_header)
```



