---
title: "Rituals of Reason: Experimental Evidence on the Social Acceptability of Lotteries in Allocation Problems"
date: 2025-04-09
author:
  - name: Elias Bouacida
    url: https://www.bouacida.fr
    orcid: 0000-0001-8656-6678
    affiliation: University Paris 8
  - name: Renaud Foucart
    url: https://sites.google.com/site/renaudfoucart/
    orcid: 0000-0003-0611-6146
    affiliation: Lancaster University Management School
doi: "10.1016/j.geb.2025.04.001"
categories: 
- Lotteries
- Allocation Mechanisms
- Experiment
pub-info:
  reference: >-
    <a href="https://www.bouacida.fr/">Elias Bouacida</a>, <a href="https://sites.google.com/site/renaudfoucart/">Renaud Foucart</a>, "Rituals of Reason: Experimental Evidence on the Social Acceptability of Lotteries in Allocation Problems"
  links:
    - name: Paper
      url: https://doi.org/10.1016/j.geb.2025.04.001
      icon: fa-brands fa-pdf
    - name: Code
      url: https://rituals-of-reasons-reproduction-40ab0b.gitpages.huma-num.fr/Code/Experiment1_ACleaningData.html
      icon: fa-brands fa-github
    - name: Data
      url: https://doi.org/10.57745/NZTMN9
      doi: 10.57745/NZTMN9
      icon: fa-solid fa-table

sidebar: false    
---

The latest version of the paper is available [here](https://kwnsfk27.r.eu-west-1.awstrack.me/L0/https:%2F%2Fauthors.elsevier.com%2Fsd%2Farticle%2FS0899-8256%2825%2900047-8/1/010201961b99f268-1419271e-4823-49a9-8d9f-ab7effe66e74-000000/7mPb9cgSzrjOJ4rNloQi0ODvSr8=421) and the [Online Appendices](https://ars.els-cdn.com/content/image/1-s2.0-S0899825625000478-mmc1.pdf). 
The code for the treatment of the data is available on Gitlab here at the repo [rituals-of-reasons-reproduction](https://gitlab.huma-num.fr/ebouacida/rituals-of-reasons-reproduction) and the research data [here](https://doi.org/10.57745/NZTMN9).
Accepted at *Games and Economic Behavior*.

## Abstract

We study collective preferences towards the use of random procedures in allocation mechanisms. We report the results of two experiments in which subjects choose a procedure to allocate a reward to half of them. The first possibility is an explicitly random device: the outcome of a lottery. The second is an equally unpredictable procedure with an identical success rate, but without explicit randomization. We identify an aversion to lotteries, particularly when compared to procedures reminiscent of meritocratic ones. In line with the literature, we also find evidence of a preference for control in most procedures.



## Bibtex Citation

For the paper:

```bibtex
@article{BOUACIDA2025,
title = {Rituals of Reason: Experimental Evidence on the Social Acceptability of Lotteries in Allocation Problems},
journal = {Games and Economic Behavior},
year = {2025},
issn = {0899-8256},
doi = {https://doi.org/10.1016/j.geb.2025.04.001},
url = {https://www.sciencedirect.com/science/article/pii/S0899825625000478},
author = {Elias Bouacida and Renaud Foucart},
keywords = {lotteries, mechanism design, allocation problems, procedures, tie-breaking rule, social choice},
abstract = {We study collective preferences towards the use of random procedures in allocation mechanisms. We report the results of two experiments in which subjects choose a procedure to allocate a reward to half of them. The first possibility is an explicitly random device: the outcome of a lottery. The second is an equally unpredictable procedure with an identical success rate, but without explicit randomization. We identify an aversion to lotteries, particularly when compared to procedures reminiscent of meritocratic ones. In line with the literature, we also find evidence of a preference for control in most procedures.}
}
```

For the data:

```bibtex
@data{NZTMN9_2024,
author = {Bouacida, Elias and Foucart, Renaud},
publisher = {Recherche Data Gouv},
title = {{Données de réplication pour : Rituals of Reasons: A Choice-Based Approach to the Acceptability of Lotteries in Allocation Problems}},
UNF = {UNF:6:WMWaP7x55KMxLV190+CM/Q==},
year = {2024},
version = {V1},
doi = {10.57745/NZTMN9},
url = {https://doi.org/10.57745/NZTMN9}
}
```