---
title: "Decreasing Differences in Expert Advice: Evidence from Chess Players"
date: 2024-02-02
author:
  - name: Elias Bouacida
    url: https://www.bouacida.fr
    orcid: 0000-0001-8656-6678
    affiliation: University Paris 8
  - name: Renaud Foucart
    url: https://sites.google.com/site/renaudfoucart/
    affiliation: Lancaster University Management School
    orcid: 0000-0003-0611-6146
  - name: Maya Jalloul
    url: https://www.lancaster.ac.uk/lums/people/maya-jalloul/
    affiliation: Lancaster University Management School
    orcid: 0000-0003-3440-3281
doi: ""
categories: 
- Advice
- Control
- Experiment
pub-info:
  reference: >-
    <a href="https://www.bouacida.fr/">Elias Bouacida</a>, <a href="https://sites.google.com/site/renaudfoucart/">Renaud Foucart</a>,  <a href="https://www.lancaster.ac.uk/lums/people/maya-jalloul/">Maya Jalloul</a>"Decreasing Differences in Expert Advice: Evidence from Chess Players"
  links:
    - name: Code
      url: https://decreasing-differences-ebouacida-92abd7c994ce472e25f3e62c7fbcaa.gitpages.huma-num.fr/
      icon: fa-brands fa-github
    - name: Data
      url: https://doi.org/10.57745/UL502I
      doi: 10.57745/UL502I
      icon: fa-solid fa-table
    # - name: PDF
    #   url: https://shs.hal.science/halshs-04453028/file/2024WP.pdf
    #   icon: fa-solid fa-file-pdf
sidebar: false    
---

The last version of the paper is available [here](Decreasing_Differences_in_Expert_Advice__Evidence_from_Chess_Players.pdf). 
The data is available on Recherche Data Gouv at <https://doi.org/10.57745/UL502I>.
The data analysis for reproducibility purposes is [here](https://decreasing-differences-ebouacida-92abd7c994ce472e25f3e62c7fbcaa.gitpages.huma-num.fr/).

## Abstract

We study the impact of external advice on the relative performance of chess players. We asked players in chess tournaments to evaluate positions in past games and allowed them to revise their evaluation following advice from a high or a low ability player. While high-quality advice has the potential to act as a "great equalizer," reducing the difference between high and low ability players, this is not what happens in our experiment. This is in part because our subjects ignore too much of the advice they receive. It is also because low ability players pay a higher premium than high ability ones by following their initial idea instead of high-quality advice.

## Citation

Working paper:

```bibtex
@unpublished{bouacida:halshs-04453028,
  TITLE = {{Decreasing Differences in Expert Advice: Evidence from Chess Players}},
  AUTHOR = {Bouacida, Elias and Foucart, Renaud and Jalloul, Maya},
  URL = {https://shs.hal.science/halshs-04453028},
  NOTE = {working paper or preprint},
  YEAR = {2024},
  MONTH = Feb,
  KEYWORDS = {decreasing differences ; expert ; advice ; chess ; control},
  PDF = {https://shs.hal.science/halshs-04453028/file/2024WP.pdf},
  HAL_ID = {halshs-04453028},
  HAL_VERSION = {v1},
}
```

Data:

```bibtex
@misc{UL502I_2024,
author = {Bouacida, Elias and Foucart, Renaud and Jalloul, Maya},
publisher = {Recherche Data Gouv},
title = {{Decreasing Differences in Expert Evaluations: Evidence From a Field Experiment in Chess}},
UNF = {UNF:6:O7lbRs7YE1njXRSkRhvJxg==},
year = {2024},
version = {V2},
doi = {10.57745/UL502I},
url = {https://doi.org/10.57745/UL502I},
note = {data}
}
```

